networks:
  safe-cloud-backend:

volumes:
  database-data:
  user-files:

services:
  database:
    container_name: database
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database-data:/var/lib/postgresql/data
      - user-files:/app/static
    networks:
      - safe-cloud-backend

  backend:
    container_name: backend
    image: nest-backend-app
    build: .
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - '5000:5000'
    networks:
      - safe-cloud-backend
